name: Android CICD build

on:
  push:
    branches: [ cicd-fred ]
  pull_request:
    branches: [ cicd-fred ]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # Use AdoptOpenJDK distribution
          java-version: '11'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Download dependencies
      - name: Download dependencies
        run: ./gradlew dependencies

      # Step 5: Run unit tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest